### ISSUE TITLE
Little rethinking of the directory structure

### ISSUE THREAD

**Issue by phndiaye** [upfluence/oss#15]
**Request for Comment: Rethink the files structures into a more accurate directory structure.**

Actually, the current state is not bad at all. It's really organized, in fact. But we have some things that cohabit in the same folder while they should be split, notably in the `base` directory which holds both Core stylesheets / settings and some components we have.

That's why, I propose the following structure (highly inspired by http://thesassway.com/beginner/how-to-structure-a-sass-project)
```
less/
├── upfluence-oss.less
├── core/
│   ├── _all.less
│   ├── _colors.less
│   └── _fonts.less
│   ├── _typography.less
│   ├── _variables.less
├── base/
│   ├── _all.less
│   ├── _alerts.less
│   ├── _buttons.less
│   ├── _checkboxes.less
│   ├── _icons.less
│   ├── _inputs.less
│   ├── _links.less
│   ├── _navs.less
│   ├── _tags.less
│   └── _tables.less
├── mixins/
│   ├── _all.less
│   └── _progress-radials.less
├── vendor/
│   ├── _all.less
│   ├── _data-tables.less
│   ├── _summernote.less
│   └── _modals.less
├── utilities/
│   ├── _all.less
│   ├── _grid.less
│   ├── _progress-radials.less
│   └── _typography.less
```

As you can see, first thing is, a Master Stylesheet `upfluence-oss.less` which is called by applications and imports the other styles. Second important thing is the `_all.less` in each directory which has the role of importing the related files. One effect of this is to have a pretty light Master Stylesheet.

The directories are then as follows:
* core:  Contains all of the settings that are common to all apps, and are unchangeable
* base: The styles of our base components, which are all independent, but may depend on Core and Mixins.
* mixins: Well ... Mixins. Functions used for building things.
* vendor: Because we may depend on external resources or projects with UI, here are where we style them
* utilities: Some helper classes more likely to be used in the HTML and never in the CSS itself, as we can rely on the variables (also called design tokens) there. Helper classes are useful for Layouts, where instead of creating some CSS, you can directly go with some classes for setting margins, paddings, text colors, etc.

Thanks for reading ;) And would like to have your input on this :)

**Comment by AlexisMontagne** [comment]
@phndiaye i really like the idea 👍  

Sometime the limit between `base/` and `utilities/` could be really thin. But im good with it

**Comment by phndiaye** [comment]
Actually, `base/` really concerns the Components themselves, and `utilities/` are just CSS classes usable in the HTML directly as we currently have for `text-size-X` (for text sizes) and `(padding|margin)-[xxx-sm...lg]` for spacers.

**Comment by AlexisMontagne** [comment]
Make sense 🤔 , it looks good to me then
