### ISSUE TITLE
Choose Primary and a Secondary Buttons, and roll with it

### ISSUE THREAD

**Issue by phndiaye** [upfluence/oss#16]
**Request for Comment**

This is more a discussion than an issue for choosing a Primary Button and a Secondary Button between our *solid* Orange and Purple buttons.

*By "solid" I mean buttons with background colors, in contrast with Ghost buttons which are buttons with transparent background color.* 

Until now, I have used `upf-btn--orange` and `upf-btn--purple` without real distinction, but as we are rolling out OSS in more projects, I think it might be good to define a `upf-btn--primary` and a `upf-btn--secondary`. Also, I don't see any use case for other types of buttons; except for Destructive Actions (which go with the `upf-feedback-error` color).

Only thing is, if we choose one color for the Primary Button (say, Orange) we may have to drop the other as one pattern I see in most websites and known Design Systems is that the `Secondary Button` is usually a `Ghost` one.

<img width="1023" alt="screen shot 2017-03-28 at 14 09 20" src="https://cloud.githubusercontent.com/assets/4022350/24404219/c3ddc22a-13c0-11e7-8fb7-8c0d44ea5332.png">

Would like to have your comments on that :) 

Also related to buttons, what do you think of introducing Buttons modifers for:
- Link Buttons (buttons looking like normal text — removed background, borders, and maybe padding)
- Icon buttons (we don't have the case yet, but a button reduced to a simple Icon)
- Dropdown buttons (A button opening a drodpown, as seen in the Summernote's Columns dropdown)

**Comment by phndiaye** [comment]
Request for Comment

**Comment by AlexisMontagne** [comment]
It totally make sense we should defined them.

I like the idea that the second btn is also a full one, the "ghost" one might just be used in certain situations to make the block "lighter", not to be a regular call to action

IMO:
* `upf-btn--primary`: should be `upf-btn--orange`
* `upf-btn--second`: `upf-btn--purple`.

**Comment by phndiaye** [comment]
Perfect ! Let's go with both Primary and Secondary as solid buttons then :)
